name: base # or your desired environment name
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - anaconda
  - pip:
    - google-adk
    - google-genai
    - pydantic
    - google-adk==1.18.0
    - pytest==8.4.2
    - asyncio==1.2.0
    - deprecated
    - pandas
    - tabulate
    - tqdm
    - scikit-learn
    - google-genai
    - pydantic
    - numpy
